# Generated by Django 4.0.2 on 2023-08-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='name',
        ),
    ]
