# Generated by Django 5.0.1 on 2024-01-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_rename_products_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created']},
        ),
    ]
