# Generated by Django 5.0.1 on 2024-01-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
